Feature/post pr 17 comments
TrustTheVote-Project/VTP-web-api pull request #18
Opened 2023-04-12 12:43 UTC by windoverwater

This PR is against (is on top of) [https://github.com/TrustTheVote-Project/VTP-web-api/pull/17](https://github.com/TrustTheVote-Project/VTP-web-api/pull/17) since that one has yet to be blessed.

This one adds additional test cases which prototype the best idea I am coming up without understanding the design principles, patterns, best practices etc in this space of pytest, FastAPI, pydantic, and the general space of putting together a web design and implementation.  This PR has issues, but here it is regardless.  Unfortunately, we are weeks late on a tight schedule and, well, if we don't make significant progress in the next few days, we should start planning on how to best to renege on participating in the demo.  So here is my latest tech attempt to move this project forward.

We really should talk about this asap.

Note - the pydantic stuff (the json_data_models.py file) is not in play with anything else - it is just a stand alone file capturing current thoughts.

2023-04-22 03:44 UTC, ion-oset requested changes
LGTM. Entirely formatting and capitalization.

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "US president": {
```suggestion
                "U.S. President": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "US senate": {
```suggestion
                "U.S. Senate": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "governor": {
```suggestion
                "Governor": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?": {
```suggestion
                "Question 1 - should the starting time of the annual town meeting be moved to 6:30 PM?": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                    "description": "Should the Town of Concord start the annual Town Meeting at 6:30PM instead of 7:00PM?\n",
```suggestion
                    "description": "Should the Town of Concord start the annual Town Meeting at 6:30 PM instead of 7:00 PM?\n",
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/receipts.26.csv
> +"0000 - US president","0001 - US senate","0002 - governor","0003 - County Clerk","0004 - Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?"
```suggestion
"0000 - U.S. President","0001 - U.S. Senate","0002 - Governor","0003 - County Clerk","0004 - Question 1 - should the starting time of the annual town meeting be moved to 6:30 PM?"
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/blank-ballot.json
> +                "US president": {
```suggestion
                "U.S. President": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/blank-ballot.json
> +                "US senate": {
```suggestion
                "U.S. Senate": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/blank-ballot.json
> +                "governor": {
```suggestion
                "Governor": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/blank-ballot.json
> +                "Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?": {
```suggestion
                "Question 1 - should the starting time of the annual town meeting be moved to 6:30 PM?": {
```

2023-04-22 03:44 UTC, ion-oset commented on src/vtp/web/api/data/blank-ballot.json
> +                    "description": "Should the Town of Concord start the annual Town Meeting at 6:30PM instead of 7:00PM?\n",
```suggestion
                    "description": "Should the Town of Concord start the annual Town Meeting at 6:30 PM instead of 7:00 PM?\n",
```

2023-04-22 11:31 UTC, windoverwater commented
FYI - the above comments are all good and I will add them.  However, this PR needs to refactored.  The changes in backend.py are in the wrong direction - I am in the middle of refactoring them.  FWIIW I was going to delete this PR this morning but will keep it as is so to incorporate the above. But please don’t spend more time on it until I can redo it.

2023-04-25 19:24 UTC, windoverwater commented
Just circling back again on this.  My plan is to incorporate all the proposed changes to the ballot files and create VTP-mock-election.US.14 with the corrections.  I cast a couple hundred votes into that repo and from there regenerate the above and the other now additional mock-data files.  It is not hard and it will make sure that the changes are added as intended.

2023-04-25 19:27 UTC, windoverwater commented
Also, I would like to create a brand new PR for the work other than what Ion has already reviewed above.  See ...

2023-04-26 17:55 UTC, ion-oset commented
> FWIIW I was going to delete this PR this morning but will keep it as is so to incorporate the above. But please don’t spend more time on it until I can redo it.

If you close it (without deleting it), you can still view it without it appearing as active.

2023-04-26 18:03 UTC, windoverwater commented
Oops - yes - I meant to write close it.

2023-04-26 20:37 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "US president": {
See https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:37 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "US senate": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:37 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "governor": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:38 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:38 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                    "description": "Should the Town of Concord start the annual Town Meeting at 6:30PM instead of 7:00PM?\n",
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:38 UTC, windoverwater commented on src/vtp/web/api/data/receipts.26.csv
> +"0000 - US president","0001 - US senate","0002 - governor","0003 - County Clerk","0004 - Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?"
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:38 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                "US president": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:38 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                "US senate": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:38 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                "governor": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:39 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                "Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:39 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                    "description": "Should the Town of Concord start the annual Town Meeting at 6:30PM instead of 7:00PM?\n",
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:40 UTC, closed without merging