copying blank ballot, cast ballot, ballot check to here
TrustTheVote-Project/VTP-web-api pull request #19
Opened 2023-04-12 18:01 UTC by windoverwater

Just a PR for the three data files

2023-04-22 03:38 UTC, ion-oset requested changes
Looks good to me. Mostly typographic changes.

2023-04-22 03:38 UTC, ion-oset commented on src/vtp/web/api/data/receipts.26.csv
> +"0000 - US president","0001 - US senate","0002 - governor","0003 - County Clerk","0004 - Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?"
```suggestion
"0000 - U.S. President","0001 - U.S. senate","0002 - Governor","0003 - County Clerk","0004 - Question 1 - should the starting time of the annual town meeting be moved to 6:30 PM?"
```

2023-04-22 03:38 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?": {
```suggestion
                "Question 1 - should the starting time of the annual town meeting be moved to 6:30 PM?": {
```

2023-04-22 03:38 UTC, ion-oset commented on src/vtp/web/api/data/blank-ballot.json
> +                "governor": {
```suggestion
                "Governor": {
```

2023-04-22 03:38 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "US president": {
```suggestion
                "U.S. President": {
```

2023-04-22 03:38 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "US senate": {
```suggestion
                "U.S. Senate": {
```

2023-04-22 03:38 UTC, ion-oset commented on src/vtp/web/api/data/cast-ballot.json
> +                "governor": {
```suggestion
                "Governor": {
```

2023-04-26 20:41 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                "US president": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:41 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                "US senate": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:41 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                                "Hermione  Granger"
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:41 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                    "choices": [
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:41 UTC, windoverwater commented on src/vtp/web/api/data/receipts.26.csv
> +"0000 - US president","0001 - US senate","0002 - governor","0003 - County Clerk","0004 - Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?"
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:42 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "Question 1 - should the starting time of the annual town meeting be moved to 6:30PM?": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:42 UTC, windoverwater commented on src/vtp/web/api/data/blank-ballot.json
> +                "governor": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:42 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "US president": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:42 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "US senate": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-04-26 20:42 UTC, windoverwater commented on src/vtp/web/api/data/cast-ballot.json
> +                "governor": {
https://github.com/TrustTheVote-Project/VTP-mock-election.US.14/commit/ccd386e05a84b85a6d671c5ff2dea65d9b613229

2023-05-01 14:23 UTC, windoverwater commented
The merge of PR https://github.com/TrustTheVote-Project/VTP-web-api/pull/20 makes this OBE - closing.

2023-05-01 14:23 UTC, closed without merging